server:
 port: 8090

spring:
 datasource:
  url: jdbc:postgresql://localhost:5441/order-service-db?user=root&password=toor
 liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
 jpa:
  open-in-view: false
  properties:
   hibernate:
    default_schema: public
