version: '3.8'
services:

 os-db:
  image: postgres:14.1
  container_name: os-db
  restart: always
  volumes:
   - os-posgresql:/data/lib
  environment:
   - POSTGRES_DB=order-service-db
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=toor
   - POSTGRES_HOST_AUTH_METHOD=trust
  ports:
   - '5441:5432'

volumes:
 os-posgresql:
